### PR TITLE
Create Team support

### PR DESCRIPTION
**Pull request by kimeyu**
Initial commit to support creating Teams.
Includes a basic form to submit a Team Name and Logo URL, which will save to DB.
Includes an index to view all teams, and a page to view a specific team by name.

🆗Does not include any style/formatting.
✅Does not include any tests.
==> It does now! (Rag)
✅Does not include any polish whatsoever.
==> It does now! (Rag)

----

teams

### CODE REVIEW

**Comment by carlosplusplus** [comment]
Here's an example of a `HighScore` controller / spec I generated from a scaffold:

```
rails generate scaffold HighScore game:string score:integer
```

**Controller**:

```ruby
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end
```

**Spec**:

```ruby
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe HighScoresController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HighScore. As you add validations to HighScore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HighScoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      HighScore.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      high_score = HighScore.create! valid_attributes
      get :show, params: {id: high_score.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      high_score = HighScore.create! valid_attributes
      get :edit, params: {id: high_score.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HighScore" do
        expect {
          post :create, params: {high_score: valid_attributes}, session: valid_session
        }.to change(HighScore, :count).by(1)
      end

      it "redirects to the created high_score" do
        post :create, params: {high_score: valid_attributes}, session: valid_session
        expect(response).to redirect_to(HighScore.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {high_score: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested high_score" do
        high_score = HighScore.create! valid_attributes
        put :update, params: {id: high_score.to_param, high_score: new_attributes}, session: valid_session
        high_score.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the high_score" do
        high_score = HighScore.create! valid_attributes
        put :update, params: {id: high_score.to_param, high_score: valid_attributes}, session: valid_session
        expect(response).to redirect_to(high_score)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        high_score = HighScore.create! valid_attributes
        put :update, params: {id: high_score.to_param, high_score: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested high_score" do
      high_score = HighScore.create! valid_attributes
      expect {
        delete :destroy, params: {id: high_score.to_param}, session: valid_session
      }.to change(HighScore, :count).by(-1)
    end

    it "redirects to the high_scores list" do
      high_score = HighScore.create! valid_attributes
      delete :destroy, params: {id: high_score.to_param}, session: valid_session
      expect(response).to redirect_to(high_scores_url)
    end
  end

end
```

**Comment by carlosplusplus** [comment]
**Update** by Rag:
- 🎨all style comments.
- Fixed controller logic (e.g. strong params).
- Added unit tests for controller actions.

The code 💅(polish) is here - will focus on 🎨later.

**Comment by carlosplusplus** [comment]
Next step is to implement `edit`, `update`, and `delete` @kimeyu !
https://github.com/nexusgamingseries/core/pull/11#issuecomment-446830403

This comment will show some examples ( my style was a slightly different ).

**Review by carlosplusplus — APPROVED** [review]
LGTM! 😎

**Review by cajuncanuck — APPROVED** [review]
👍🏻

**Pull request merged**
